import DeleteBook from "@/components/DeleteBooks";
import { IBook } from "@/db/models/Book";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
	title: "Ini website Book",
	description: "Generated by create next app",
};

export default async function Book() {
	const response: Response = await fetch("http://localhost:3000/api/books");
	const books: IBook[] = await response.json();

	return (
		<div>
			<h1>Book page</h1>
			<ul>
				{books.map((book) => (
					<li key={book._id.toString()}>
						{book.title} | <Link href={`/book/${book._id}`}>Detail</Link> |{" "}
						<DeleteBook bookId={book._id.toString()} />
					</li>
				))}
			</ul>
		</div>
	);
}
